version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run: # run tests
      #     name: Run Test and Coverage
      #     command: |
      #       yarn test -- --coverage
      - deploy:
          name: "deploy develop to beta"
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              export TARGET=beta
              yarn build
              sudo apt-get -y -qq update
              sudo apt-get -y -qq install python3.5-dev
              curl -O https://bootstrap.pypa.io/get-pip.py
              python3.5 get-pip.py --user
              ~/.local/bin/pip install awscli --upgrade --user
              ~/.local/bin/aws s3 sync ~/project/build s3://any-services.snappykit.constructor --delete
              ~/.local/bin/aws cloudfront create-invalidation --distribution-id E2NW1D0XBGXS0P --paths '/*'
            fi
